name: First Workflow
on: 
  workflow_dispatch:
  push:
    branches: 
      - main
      - 'dev/**'
      - 'feature/**'
    paths-ignore:
      - '.github/workflow/*'
  pull_request:
    types:
      - opened
      - closed
  

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: |
            echo "Hello World"
            echo "Hello World 2nd time"
      - name: Print Goodbye
        run: echo "Goodbye!"
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-e2e
          path: |
            requirements.txt
            data/steps.csv
