name: First Workflow
on: 
  workflow_dispatch:
  push:
    branches: 
      - main
      - 'dev/**'
      - 'feature/**'
    paths-ignore:
      - '.github/workflow/*'
  pull_request:
    types:
      - opened
      - closed

jobs:
  first-job:
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Print Greeting
        run: |
            echo "Hello World"
            echo "Hello World 2nd time"
      - name: Print Goodbye
        run: echo "Goodbye!"
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Publish csv filename
        id: publish
        run: find data/steps.csv -type f -execdir echo 'script-file={} >> $GITHUB_OUTPUT' ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-e2e
          path: |
            requirements.txt
            data/steps.csv
  deploy:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with: 
          name: artifacts-e2e
      - name: Lisy the content
        run: ls 
      - name: Output filename
        run: echo "${{ needs.first-job.outputs.script-file }}"
      - name: Running deploy job
        run: echo "Deploying"