name: Test Project

on: workflow_dispatch

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Start Testing the Project
              run: echo "Testing the Project"
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: show dir
              run: ls
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10' 
            - run: python test_script.py